GET http://localhost:3000/api/watches

###

GET http://localhost:3000/api/watches/1

###

POST http://localhost:3000/api/watches
Content-Type: application/json

{
    "imageUrl": "",
    "price": 100.55,
    "brand": "BadWatches",
    "desc": "A Cheap Watch",
    "caseColour": "Black",
    "bandColour": "Silver",
    "bandType": "Rubber",
    "movementType": "Digital",
    "faceSize": "40mm",
    "stock": 3
}

###

DELETE http://localhost:3000/api/watches/3

###

PATCH http://localhost:3000/api/watches/1
Content-Type: application/json

{
    "price": 55000.22,
    "faceSize": "600mm"
}
